version: 1.0.{build}
clone_folder: c:\mg
environment:
  ACCESS_KEY:
    secure: 4U3SfYBNNlc0VXB/9kPvqFH0qbzOD3FXHIY7SuRFvcQ=
  SECRET_KEY:
    secure: PtL0a/tSy8HJbUiwu8GNvx+UfOeOiSTrqGxmGswskxs8EBVLIJX5k2LgnX85V45G

  matrix:
#    - myarch: x64

    - myarch: Win32

build_script:
- cmd: >-
    cd %APPVEYOR_BUILD_FOLDER%

    git submodule update --init

    @echo on

    build.cmd
