version: 1.0.{build}
clone_folder: c:\mg
environment:
  MSYS2_DIR: msys64
  MSYSTEM: MINGW64
  ACCESS_KEY:
    secure: 3texJQ9qOmxfs/YUAYKttYberiUlkyodicdX+NRKOl4=
  SECRET_KEY:
    secure: ZFGXS5xgtCJ4hzkYuH8c8h1FIg1eYWMW2SzwYmjZrzw4aQQNFlZP+je6inXK2Mov
build_script:
- cmd: >-
    cd %APPVEYOR_BUILD_FOLDER%

    git submodule update --init

    @echo on

    SET "PATH=C:\%MSYS2_DIR%\%MSYSTEM%\bin;C:\%MSYS2_DIR%\usr\bin;%PATH%"

    bash -c "pacman -Syu --noconfirm"

    bash -c "pacman -S --needed --noconfirm mingw-w64-x86_64-nasm mingw-w64-x86_64-freetype mingw-w64-x86_64-libpng mingw-w64-x86_64-libsamplerate mingw-w64-x86_64-SDL2 mingw-w64-x86_64-jasper mingw-w64-x86_64-qt5-static mingw-w64-x86_64-python3-pip zip"

    cd %APPVEYOR_BUILD_FOLDER%

    bash -c "python3 -m pip install awscli"

    bash -c "export AWS_ACCESS_KEY_ID=$ACCESS_KEY; export AWS_SECRET_ACCESS_KEY=$SECRET_KEY; ./build.sh aws"
